"""Learnt sth new about foreignkeys

Revision ID: 0a33087a8341
Revises: 59e1b11b6e5c
Create Date: 2026-04-22 13:03:59.280352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a33087a8341'
down_revision: Union[str, Sequence[str], None] = '59e1b11b6e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
